channels:
  - http://ssb.stsci.edu/astroconda-dev

dependencies:
  - python>=3
  - setuptools
  - asdf
  - astropy
  - crds
  - dask
  - drizzle
  - gwcs
  - jsonschema
  - jplephem
  - matplotlib
  - namedlist
  - numpy
  - photutils
  - pymssql
  - scipy
  - six
  - stsci.image
  - stsci.imagestats
  - verhawk
  - sphinx_rtd_theme
  - pip:
    - sphinx-automodapi
    - stsci_rtd_theme
