
dependencies:
  - python>=3
  - setuptools
  - astropy
  - matplotlib
  - numpy
  - scipy
  - pip:
    - sphinxcontrib-programoutput
    - sphinx-automodapi
    - stsci_rtd_theme
    - asdf
    - crds
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - six
    - verhawk
    - sphinx_rtd_theme

