channels:
  - http://ssb.stsci.edu/astroconda-dev

dependencies:
  - asdf
  - astropy
  - crds
  - drizzle
  - gwcs
  - jsonschema
  - jplephem
  - matplotlib
  - namedlist
  - numpy
  - photutils
  - scipy
  - six
  - spherical-geometry
  - stsci.image
  - stsci.imagestats
  - stsci.stimage
  - stsci.tools
  - verhawk
  - sphinx_rtd_theme
  - pip:
    - sphinx-automodapi
    - stsci_rtd_theme
