dist: xenial
language: python
python: 3.7.5

sudo: false

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz
      - liblapack-dev

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - TEST_COMMAND='pytest --cov-report=xml --cov=./'
    - PIP_DEPENDENCIES='.[test]'

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - python: 3.6.9
    - python: 3.7.5
    - python: 3.8.0

    - env: PIP_DEPENDENCIES='numpy~=1.16.0 .[test]'
      python: 3.6.9

    - env: PIP_DEPENDENCIES='numpy~=1.17.0 .[test]'
      python: 3.7.5

    # Test with SDP pinned dependencies
    - env: PIP_DEPENDENCIES='-r requirements-sdp.txt .'
      python: 3.7.5

    # Test with dev dependencies
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    # Test with latest delivered CRDS_CONTEXT, as in regressions tests
    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='make --directory=docs html'
           PIP_DEPENDENCIES='.[docs]'

    # PEP8 check
    - env: TEST_COMMAND='flake8'
           PIP_DEPENDENCIES='flake8'

  allow_failures:
    - env: PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - env: CRDS_CONTEXT="jwst-edit"
           PIP_DEPENDENCIES=".[test]"

install:
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

after_success:
  - if [[ ${TEST_COMMAND} =~ ^pytest ]]; then codecov -F unit; fi
