os: linux
dist: xenial
language: python
python: 3.8.5

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - PIP_DEPENDENCIES=.[test]

cache:
  - pip
  - directories:
    - /tmp/crds_cache

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Latest dependency versions w/coverage
      script:
        - pytest --cov-report=xml --cov=./
      after_success:
        - codecov -F unit

    - name: Oldest dependency versions
      python: 3.6.10
      before_install:
        - pip install . --no-deps
        - minimum_deps
      env:
        PIP_DEPENDENCIES="-r requirements-min.txt .[test]"
      install:
        - pip install -U pip certifi
        - pip install $PIP_DEPENDENCIES
        # Since there is no version of stdatamodels on PyPI, install from
        # Github master until it is released to PyPI
        - pip install git+https://github.com/spacetelescope/stdatamodels

    - name: SDP dependencies in requirements-sdp.txt, CRDS_CONTEXT=jwst-edit
      env:
        PIP_DEPENDENCIES="-r requirements-sdp.txt .[test]"
        CRDS_CONTEXT=jwst-edit

    - name: Dev dependencies in requirements-dev.txt
      env:
        PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - name: Warnings treated as Exceptions
      script:
        - pytest -W error

    - name: Documentation build
      env:
        PIP_DEPENDENCIES=.[docs]
      script:
        - sphinx-build -W docs docs/_build
      addons:
        apt:
          packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

    - name: Code style check
      script:
        - flake8

    - name: Verify install_requires in setup.py
      env:
        PIP_DEPENDENCIES=.
      script:
        - verify_install_requires

    - name: Build distribution
      env:
        PIP_DEPENDENCIES="pep517 twine"
      script:
        - python -m pep517.check .
        - python -m pep517.build .
        - twine check dist/*

    - name: Security check
      env:
        PIP_DEPENDENCIES=".[test] bandit"
      script:
        - bandit -r jwst scripts -c .bandit.yaml -ll

  allow_failures:
    - name: Dev dependencies in requirements-dev.txt
      env:
        PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"

    - name: Warnings treated as Exceptions
      script:
        - pytest -W error

install:
  - pip install $PIP_DEPENDENCIES

script:
  - pytest
