language: c

os:
    - linux
    - osx

sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev'
        - CONDA_DEPENDENCIES='pytest jwst sphinx'
        - CONDA_JWST_DEPENDENCIES='pytest jwst sphinx'
        - PIP_DEPENDENCIES=''
        - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
        - CRDS_PATH='/tmp/crds_cache'
        - NUMPY_VERSION=1.11

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='install'
        - PYTHON_VERSION=2.7 SETUP_CMD='test'
        - PYTHON_VERSION=3.5 SETUP_CMD='install'
        - PYTHON_VERSION=3.5 SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # PEP8 check with pycodestyle (only once, i.e. "os: linux")
        - os: linux
          env: PYTHON_VERSION=3.5 MAIN_CMD='pycodestyle --count'
               SETUP_CMD='jwst' TEST_CMD='pycodestyle --version'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES

        # build sphinx documentation with warnings
        - os: linux
          env: PYTHON_VERSION=3.5 
               SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme sphinx-automodapi'

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: PYTHON_VERSION=3.5 MAIN_CMD='pycodestyle --count'
               SETUP_CMD='jwst' TEST_CMD='pycodestyle --version'
               CONDA_DEPENDENCIES=$CONDA_JWST_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD
