os: linux
dist: xenial
language: python
python: 3.8.2

env:
  global:
    - CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    - CRDS_PATH=/tmp/crds_cache
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - TEST_COMMAND="pytest --cov-report=xml --cov=./"
    - PIP_DEPENDENCIES=.[test]

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Latest dependency versions

    - name: Oldest dependency versions
      python: 3.6.10
      env:
        GEN_MIN_DEPS=true
        PIP_DEPENDENCIES="-r requirements-min.txt .[test]"

    - name: SDP dependencies in requirements-sdp.txt, CRDS_CONTEXT=jwst-edit
      python: 3.7.7
      env:
        PIP_DEPENDENCIES="-r requirements-sdp.txt .[test]"
        CRDS_CONTEXT=jwst-edit
        TEST_COMMAND=pytest

    - name: Dev dependencies in requirements-dev.txt
      env:
        PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
        TEST_COMMAND=pytest

    - name: Warnings treated as Exceptions
      env:
        TEST_COMMAND="pytest -W error"

    - name: Documentation build
      env:
        PIP_DEPENDENCIES=.[docs]
        TEST_COMMAND="make html --directory=docs"
      addons:
        apt:
          packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

    - name: Code style check
      env:
        PIP_DEPENDENCIES=flake8
        TEST_COMMAND=flake8

    - name: Verify install_requires in setup.py
      env:
        PIP_DEPENDENCIES=.
        TEST_COMMAND=verify_install_requires

  allow_failures:
    - name: Dev dependencies in requirements-dev.txt
      env:
        PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
        TEST_COMMAND=pytest

    - name: Warnings treated as Exceptions
      env:
        TEST_COMMAND="pytest -W error"

before_install:
  # For the case where we want to build with the minimum versions allowed by
  # setup.py
  - if [[ ${GEN_MIN_DEPS} = "true" ]]; then
      pip install . --no-deps;
      minimum_deps;
    fi

install:
  - pip install $PIP_DEPENDENCIES

script:
  - $TEST_COMMAND

after_success:
  - if [[ ${TEST_COMMAND} =~ ^pytest ]]; then
      codecov -F unit;
    fi
