id: asdf://stsci.edu/jwst_pipeline/manifests/jwst_transforms-1.0.0
extension_uri: asdf://stsci.edu/jwst_pipeline/extensions/jwst_transforms-1.0.0
title: JWST Transform extension 1.0.0
description: |-
  A set of tags for serializing data transforms for the JWST pipeline.
asdf_standard_requirement:
  gte: 1.5.0
tags:
- tag_uri: "tag:stsci.edu:jwst_pipeline/nircam_grism_dispersion-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/nircam_grism_dispersion-1.0.0
  title: NIRCAM Grism dispersion model
  description: |-
    Supports two models:
    Given x, y, wave, order in effective direct image returns
    x,y,wave,order in dispersed
    Given x, y, x0, y0, order in dispersed image returns x, y, wave, order
    in effective direct
- tag_uri: "tag:stsci.edu:jwst_pipeline/niriss_grism_dispersion-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/niriss_grism_dispersion-1.0.0
  title: NIRISS Grism dispersion model
  description: |-
    Supports two models:
    Given x, y, wave, order in effective direct image returns
    x, y, wave, order in dispersed
    Given x, y, x0, y0, order in dispersed image returns
    x, y, wave, order in effective direct
- tag_uri: "tag:stsci.edu:jwst_pipeline/gwa_to_slit-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/gwa_to_slit-1.0.0
  title: NIRSPEC set of models from GWA to slit_frame.
  description: |-
    This model is used by the NIRSPEC WCS pipeline.
    It maps slit to the transform from the Grating Wheel Assembly (GWA)
    to the coordinate frame of the slit, where (0, 0) is the center of
    the slit.
- tag_uri: "tag:stsci.edu:jwst_pipeline/slit_to_msa-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/slit_to_msa-1.0.0
  title: NIRSPEC set of models from slit_frame to the MSA frame.
  description: |-
    This model is used by the NIRSPEC WCS pipeline.
    It maps a slit to its position in the MSA plane.
- tag_uri: "tag:stsci.edu:jwst_pipeline/logical-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/logical-1.0.0
  title: A model performing logical operations on arrays.
  description: |-
    Implements the Numpy logical operators
- tag_uri: "tag:stsci.edu:jwst_pipeline/niriss_soss-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/niriss_soss-1.0.0
  title: NIRISS SOSS transforms.
  description: |-
    This model is used by the NIRISS SOSS WCS pipeline.
    It maps spectral order to transform
- tag_uri: "tag:stsci.edu:jwst_pipeline/refraction_index_from_prism-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/refraction_index_from_prism-1.0.0
  title: Computes the refraction index for the NIRSpec prism.
  description: |-
    Given the prism angle and the incident and refracted angles, compute the
    index of refraction.
- tag_uri: "tag:stsci.edu:jwst_pipeline/miri_ab2slice-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/miri_ab2slice-1.0.0
  title: MIRI MRS (alpha, beta) to slice number transform.
  description: |-
    This model is used by the MIRI MRS WCS pipeline.
    Given a (beta, ) coordinate it computes the slice number
    that the coordinate belongs to in detector coordinates.
- tag_uri: "tag:stsci.edu:jwst_pipeline/rotation_sequence-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/rotation_sequence-1.0.0
  title: A sequence of 3D rotations.
  description: |-
    A sequence of 3D rotations around different axes.
- tag_uri: "tag:stsci.edu:jwst_pipeline/snell-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/snell-1.0.0
  title: NIRSpec transforms through the prism.
  description: |-
    This model does all transforms through the NIRSpec prism:
    - computes the refraction index as a function of lambda.
    - Applies Snell's law through front surface.
    - Rotates to back surface.
    - Applies reflection from back surface.
    - Rotates to front surface
    - Applies Snell's law through front surface.
- tag_uri: "tag:stsci.edu:jwst_pipeline/grating_equation-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/grating_equation-1.0.0
  title: A grating equation model.
  description: |-
    Supports two models:
    - Given incident angle and wavelength compute the refraction/diffraction angle.
    - Given an incident angle and a refraction angle compute the wavelength.
- tag_uri: "tag:stsci.edu:jwst_pipeline/coords-1.0.0"
  schema_uri: http://stsci.edu/schemas/jwst_pipeline/coords-1.0.0
  title: Convert coordinates between vector and directional cosine form.
  description: |-
    This schema is for representing any model that takes coordinates and does
    some computation with them. Models have no parameters. Currently it supports
    DirCos2Unitless, Unitless2DirCos.
